// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDCK-kdyerAfNZdGAVNHG4HkofzC3IC4',
    appId: '1:769348006912:web:be285c6bb3def80b9b14e5',
    messagingSenderId: '769348006912',
    projectId: 'smartfiber-dcd4b',
    authDomain: 'smartfiber-dcd4b.firebaseapp.com',
    storageBucket: 'smartfiber-dcd4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF11eofLj22R20Tj2KdUCSiReyDa9lbJA',
    appId: '1:769348006912:android:b4caa9e3a2c36a599b14e5',
    messagingSenderId: '769348006912',
    projectId: 'smartfiber-dcd4b',
    storageBucket: 'smartfiber-dcd4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjWA4GeGrwGzDuYrRNMD53c7f9hABI7PU',
    appId: '1:769348006912:ios:ca92937dba07cf499b14e5',
    messagingSenderId: '769348006912',
    projectId: 'smartfiber-dcd4b',
    storageBucket: 'smartfiber-dcd4b.firebasestorage.app',
    iosBundleId: 'com.example.smartfiber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjWA4GeGrwGzDuYrRNMD53c7f9hABI7PU',
    appId: '1:769348006912:ios:ca92937dba07cf499b14e5',
    messagingSenderId: '769348006912',
    projectId: 'smartfiber-dcd4b',
    storageBucket: 'smartfiber-dcd4b.firebasestorage.app',
    iosBundleId: 'com.example.smartfiber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSDCK-kdyerAfNZdGAVNHG4HkofzC3IC4',
    appId: '1:769348006912:web:bdc15d242bd20a749b14e5',
    messagingSenderId: '769348006912',
    projectId: 'smartfiber-dcd4b',
    authDomain: 'smartfiber-dcd4b.firebaseapp.com',
    storageBucket: 'smartfiber-dcd4b.firebasestorage.app',
  );

}